version: '3.8'

services:
  app:
    build: .
    ports:
      - "8030:3000"
    environment:
      NODE_OPTIONS: "--max_old_space_size=4096"
    command: pnpm --filter=nc-gui run start
    restart: always